proxy:
  container_name: proxy
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
rest:
  container_name: rest
  image: node:0.10
  privileged: true
  links:
    - proxy
  environment:
    - PORT=3030
  ports:
    - "3030:3030"
  volumes:
    - ../albicilla-rest:/myapp:ro
  working_dir: /myapp
  command: node app.js
api:
  container_name: api
  image: node:0.10
  privileged: true
  links:
    - proxy
  environment:
    - PORT=3020
    - VIRTUAL_HOST=api.albicilla.com
    - VIRTUAL_PORT=3020
  ports:
    - "3020:3020"
  volumes:
    - ../albicilla-api:/myapp:ro
  working_dir: /myapp
  command: node app.js
api-v4:
  container_name: api-v4
  image: node:0.10
  privileged: true
  links:
    - proxy
    - rest
  environment:
    - NODE_LOGGING=debug
    - PORT=3050
    - VIRTUAL_HOST=api_v4.albicilla.com
    - VIRTUAL_PORT=3050
  ports:
    - "3050:3050"
  volumes:
    - ../albicilla-api-v4/:/myapp:ro
  working_dir: /myapp
  command: node app.js
public:
  container_name: public
  image: node:0.10
  privileged: true
  links:
    - proxy
    - api
  environment:
    - PORT=3000
    - VIRTUAL_HOST=www.albicilla.com
    - VIRTUAL_PORT=3000
  ports:
    - "3000:3000"
  volumes:
    - ../albicilla-public:/myapp:ro
  working_dir: /myapp
  command: node app.js
gentilis:
  container_name: gentilis
  image: tradesparq/php-apache2
  privileged: true
  links:
    - proxy
    - api
  environment:
    - VIRTUAL_HOST=user.albicilla.com
    - VIRTUAL_PORT=80
  ports:
    - "8080:80"
  volumes:
    - ../gentilis:/var/www/html
user3:
  container_name: user3
  image: digitallyseamless/nodejs-bower-grunt:0.10
  privileged: true
  links:
    - proxy
  environment:
    - VIRTUAL_HOST=user3.albicilla.com
    - VIRTUAL_PORT=9000
  ports:
    - "9000:9000"
    - "35729:35729"
  volumes:
    - ../albicilla-user:/myapp
  working_dir: /myapp
  command: grunt serve
